"""Core benchmarking abstractions."""

from quantum_backend_bench.core.benchmark_spec import (
    BenchmarkSpec,
    CircuitOperation,
    InternalCircuit,
)
from quantum_backend_bench.core.circuit_export import (
    export_benchmark_circuit,
    import_openqasm_circuit,
)
from quantum_backend_bench.core.circuit_translate import (
    TRANSLATION_INPUT_FORMATS,
    TRANSLATION_OUTPUT_FORMATS,
    TRANSLATION_VERIFY_MODES,
    TranslationDiagnostic,
    TranslationError,
    TranslationResult,
    TranslationVerification,
    emit_circuit_source,
    import_circuit_source,
    translate_circuit_source,
    translation_check_report,
    translation_error_report,
    translation_result_report,
    verify_translation,
)
from quantum_backend_bench.core.diagnostics import diagnose_result_parity
from quantum_backend_bench.core.exact import (
    exact_amplitudes,
    exact_probabilities,
    pauli_z_expectation,
)
from quantum_backend_bench.core.hardware import write_hardware_artifacts
from quantum_backend_bench.core.observable_translate import (
    HAMILTONIAN_INPUT_FORMATS,
    HAMILTONIAN_OUTPUT_FORMATS,
    HAMILTONIAN_VERIFY_MODES,
    HamiltonianVerification,
    PauliHamiltonian,
    PauliTerm,
    emit_hamiltonian_source,
    hamiltonian_check_report,
    hamiltonian_translation_report,
    import_hamiltonian_source,
    translate_hamiltonian_source,
    translation_capability_rows,
    verify_hamiltonian_translation,
)
from quantum_backend_bench.core.workflow_translate import (
    GROUPING_STRATEGIES,
    RESULT_INPUT_FORMATS,
    RESULT_OUTPUT_FORMATS,
    WORKFLOW_INPUT_FORMATS,
    WORKFLOW_OUTPUT_FORMATS,
    WORKFLOW_VERIFY_MODES,
    MeasurementRequest,
    NeutralResult,
    ParameterizedWorkflow,
    WorkflowOperation,
    canonical_workflow,
    emit_workflow_source,
    group_pauli_terms,
    group_pauli_terms_source,
    import_result_source,
    import_workflow_source,
    normalize_result_source,
    translate_workflow_source,
    verify_workflow_translation,
    workflow_translation_report,
)
from quantum_backend_bench.core.sweeps import expand_benchmark_sweep, parse_sweep_specs
from quantum_backend_bench.core.draw import draw_benchmark
from quantum_backend_bench.core.diff import (
    compare_result_sets,
    diff_passed,
    format_diff_table,
    load_result_file,
)
from quantum_backend_bench.core.doctor import doctor_checks, doctor_passed, format_doctor_table
from quantum_backend_bench.core.factory import BENCHMARK_BUILDERS, build_benchmark_from_config
from quantum_backend_bench.core.runner import run_benchmark

__all__ = [
    "pauli_z_expectation",
    "import_openqasm_circuit",
    "exact_amplitudes",
    "HAMILTONIAN_INPUT_FORMATS",
    "HAMILTONIAN_OUTPUT_FORMATS",
    "HAMILTONIAN_VERIFY_MODES",
    "GROUPING_STRATEGIES",
    "RESULT_INPUT_FORMATS",
    "RESULT_OUTPUT_FORMATS",
    "WORKFLOW_INPUT_FORMATS",
    "WORKFLOW_OUTPUT_FORMATS",
    "WORKFLOW_VERIFY_MODES",
    "HamiltonianVerification",
    "MeasurementRequest",
    "NeutralResult",
    "ParameterizedWorkflow",
    "PauliHamiltonian",
    "PauliTerm",
    "WorkflowOperation",
    "emit_hamiltonian_source",
    "hamiltonian_check_report",
    "hamiltonian_translation_report",
    "canonical_workflow",
    "emit_workflow_source",
    "group_pauli_terms",
    "group_pauli_terms_source",
    "import_hamiltonian_source",
    "import_result_source",
    "import_workflow_source",
    "normalize_result_source",
    "translate_hamiltonian_source",
    "translate_workflow_source",
    "translation_capability_rows",
    "verify_hamiltonian_translation",
    "verify_workflow_translation",
    "workflow_translation_report",
    "write_hardware_artifacts",
    "parse_sweep_specs",
    "export_benchmark_circuit",
    "expand_benchmark_sweep",
    "exact_probabilities",
    "diagnose_result_parity",
    "BENCHMARK_BUILDERS",
    "BenchmarkSpec",
    "CircuitOperation",
    "InternalCircuit",
    "build_benchmark_from_config",
    "compare_result_sets",
    "diff_passed",
    "doctor_checks",
    "doctor_passed",
    "draw_benchmark",
    "format_diff_table",
    "format_doctor_table",
    "load_result_file",
    "TRANSLATION_INPUT_FORMATS",
    "TRANSLATION_OUTPUT_FORMATS",
    "TRANSLATION_VERIFY_MODES",
    "TranslationDiagnostic",
    "TranslationError",
    "TranslationResult",
    "TranslationVerification",
    "emit_circuit_source",
    "import_circuit_source",
    "translate_circuit_source",
    "translation_check_report",
    "translation_error_report",
    "translation_result_report",
    "verify_translation",
    "run_benchmark",
]
