"""Create reproducible result bundles."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from quantum_backend_bench.core.dataframe import results_to_records
from quantum_backend_bench.core.report import format_markdown_report, load_report_input
from quantum_backend_bench.utils.io import save_csv, save_json
from quantum_backend_bench.utils.plotting import (
    save_counts_heatmap,
    save_distribution_plot,
    save_runtime_depth_plot,
    save_suite_runtime_plot,
)


def create_result_bundle(
    results_path: str | Path,
    output_dir: str | Path,
    *,
    title: str = "Quantum Backend Benchmark Bundle",
    include_plots: bool = True,
) -> dict[str, str]:
    """Create a directory containing normalized result artifacts and a README."""

    bundle = load_report_input(results_path)
    results = list(bundle.get("results", []))
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)

    paths: dict[str, str] = {}
    paths["json"] = str(save_json(results, destination / "results.json"))
    paths["csv"] = str(save_csv(results, destination / "results.csv"))
    paths["records_json"] = str(
        save_json(results_to_records(results), destination / "records.json")
    )

    report_path = destination / "report.md"
    report_path.write_text(
        format_markdown_report({**bundle, "results": results}, title=title), encoding="utf-8"
    )
    paths["report"] = str(report_path)

    environment = _first_environment(results) or bundle.get("environment") or {}
    if environment:
        paths["environment"] = str(save_json(environment, destination / "environment.json"))

    plot_errors: list[str] = []
    if include_plots and results:
        plot_errors.extend(
            _try_plot(
                paths,
                "runtime_depth_plot",
                save_runtime_depth_plot,
                results,
                destination / "runtime_depth.png",
            )
        )
        plot_errors.extend(
            _try_plot(
                paths,
                "suite_runtime_plot",
                save_suite_runtime_plot,
                results,
                destination / "suite_runtime.png",
            )
        )
        plot_errors.extend(
            _try_plot(
                paths,
                "distribution_plot",
                save_distribution_plot,
                results,
                destination / "distribution.png",
            )
        )
        plot_errors.extend(
            _try_plot(
                paths, "heatmap_plot", save_counts_heatmap, results, destination / "heatmap.png"
            )
        )

    readme_path = destination / "README.md"
    readme_path.write_text(
        _bundle_readme(results_path, title, paths, plot_errors), encoding="utf-8"
    )
    paths["readme"] = str(readme_path)
    return paths


def _try_plot(
    paths: dict[str, str], key: str, func: Any, results: list[dict[str, Any]], path: Path
) -> list[str]:
    try:
        paths[key] = str(func(results, path))
        return []
    except (RuntimeError, ValueError, ImportError) as exc:
        return [f"{key}: {exc}"]


def _bundle_readme(
    source: str | Path,
    title: str,
    paths: dict[str, str],
    plot_errors: list[str],
) -> str:
    lines = [
        f"# {title}",
        "",
        "This directory is a reproducible benchmark result bundle generated by `quantum-bench bundle`.",
        "",
        "## Source",
        "",
        f"- input: `{source}`",
        "",
        "## Files",
        "",
    ]
    for key, path in sorted(paths.items()):
        lines.append(f"- `{Path(path).name}`: {key.replace('_', ' ')}")
    if plot_errors:
        lines.extend(["", "## Plot Notes", ""])
        for error in plot_errors:
            lines.append(f"- {error}")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "Runtime values are local-environment measurements. Use `environment.json`, backend caveats in `report.md`, and the raw JSON/CSV files when comparing or publishing results.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _first_environment(results: list[dict[str, Any]]) -> dict[str, Any] | None:
    for result in results:
        environment = result.get("metadata", {}).get("environment")
        if isinstance(environment, dict):
            return environment
    return None
